[project]
name = "mcp-server-template"
version = "0.1.0"
description = "MCP Server Template written in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.6.0",
]
