name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: {% raw %}${{ github.repository }}{% endraw %}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${% raw %}{{ env.REGISTRY }}{% endraw %}
          username: ${% raw %}{{ github.actor }}{% endraw %}
          password: ${% raw %}{{ secrets.GITHUB_TOKEN }}{% endraw %}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${% raw %}{{ env.REGISTRY }}{% endraw %}/${% raw %}{{ env.IMAGE_NAME }}{% endraw %}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={% raw %}{{ version }}{% endraw %}
            type=semver,pattern={% raw %}{{ major }}{% endraw %}.{% raw %}minor }}{% endraw %}
            type=semver,pattern={% raw %}{{ major }}{% endraw %}
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${% raw %}{{ github.event_name != 'pull_request' }}{% endraw %}
          tags: ${% raw %}{{ steps.meta.outputs.tags }}{% endraw %}
          labels: ${% raw %}{{ steps.meta.outputs.labels }}{% endraw %}
          cache-from: type=gha
          cache-to: type=gha,mode=max
